name: spo
channels:
  - defaults
dependencies:
  - python=3.10.13
  - pip
  - pip:
      - torch==2.3.0
      - torchelastic==0.2.2
      - torchvision==0.18.0
      - absl-py==2.1.0
      - accelerate==0.24.1
      - addict==2.4.0
      - aliyun-python-sdk-core==2.14.0
      - aliyun-python-sdk-kms==2.16.2
      - annotated-types==0.6.0
      - appdirs==1.4.4
      - asttokens==2.0.5
      - astunparse==1.6.3
      - attrs==23.1.0
      - backcall==0.2.0
      - beautifulsoup4==4.12.2
      - boltons==23.0.0
      - brotlipy==0.7.0
      - certifi==2023.7.22
      - cffi==1.15.1
      - chardet==4.0.0
      - charset-normalizer==2.0.4
      - click==8.0.4
      - colorama==0.4.6
      - contextlib2==21.6.0
      - contourpy==1.2.0
      - crcmod==1.7
      - cryptography==41.0.3
      - cycler==0.12.1
      - decorator==5.1.1
      - deepspeed==0.12.3
      - diffusers==0.26.1
      - dnspython==2.4.2
      - docker-pycreds==0.4.0
      - einops==0.7.0
      - exceptiongroup==1.0.4
      - executing==0.8.3
      - expecttest==0.1.6
      - fairscale==0.4.13
      - filelock==3.9.0
      - fonttools==4.44.0
      - fsspec==2023.9.2
      - ftfy==6.2.0
      - gitdb==4.0.11
      - GitPython==3.1.40
      - gmpy2==2.1.2
      - hjson==3.1.0
      - huggingface-hub==0.23.0
      - hypothesis==6.87.2
      - idna==3.4
      - importlib-metadata==6.8.0
      - inflect==6.0.4
      - ipython==8.15.0
      - jedi==0.18.1
      - Jinja2==3.1.2
      - jmespath==0.10.0
      - joblib==1.4.2
      - jsonpatch==1.32
      - jsonpointer==2.1
      - kiwisolver==1.4.5
      - libarchive-c==2.9
      - Markdown==3.5.1
      - markdown-it-py==3.0.0
      - MarkupSafe==2.1.1
      - matplotlib==3.8.1
      - matplotlib-inline==0.1.6
      - mdurl==0.1.2
      - mkl-fft==1.3.8
      - mkl-random==1.2.4
      - mkl-service==2.4.0
      - ml-collections==0.1.1
      - mmengine==0.9.1
      - model-index==0.1.11
      - more-itertools==8.12.0
      - mpmath==1.3.0
      - networkx==3.1
      - ninja==1.11.1.1
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.1.105
      - opencv-python==4.8.1.78
      - opendatalab==0.0.10
      - openmim==0.3.9
      - openxlab==0.0.28
      - ordered-set==4.1.0
      - oss2==2.17.0
      - packaging==23.1
      - pandas==2.1.3
      - parso==0.8.3
      - peft==0.10.0
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - Pillow==10.0.1
      - pip==23.2.1
      - pkginfo==1.9.6
      - platformdirs==4.0.0
      - pluggy==1.0.0
      - prompt-toolkit==3.0.36
      - protobuf==4.25.0
      - psutil==5.9.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - py-cpuinfo==9.0.0
      - pycosat==0.6.6
      - pycparser==2.21
      - pycryptodome==3.19.0
      - pydantic==1.10.9
      - pydantic_core==2.14.1
      - Pygments==2.15.1
      - pynvml==11.5.0
      - pyOpenSSL==23.2.0
      - pyparsing==3.1.1
      - PySocks==1.7.1
      - python-dateutil==2.8.2
      - python-etcd==0.4.5
      - pytz==2023.3.post1
      - PyYAML==6.0
      - regex==2023.10.3
      - requests==2.28.2
      - rich==13.4.2
      - ruamel.yaml==0.17.21
      - ruamel.yaml.clib==0.2.6
      - safetensors==0.4.3
      - scikit-learn==1.4.2
      - scipy==1.13.0
      - seaborn==0.13.2
      - sentencepiece==0.1.99
      - sentry-sdk==1.35.0
      - setproctitle==1.3.3
      - setuptools==60.2.0
      - six==1.16.0
      - smmap==5.0.1
      - sortedcontainers==2.4.0
      - soupsieve==2.5
      - stack-data==0.2.0
      - sympy==1.11.1
      - tabulate==0.9.0
      - termcolor==2.3.0
      - threadpoolctl==3.5.0
      - timm==0.6.13
      - tokenizers==0.19.1
      - tomli==2.0.1
      - toolz==0.12.0
      - tqdm==4.65.0
      - traitlets==5.7.1
      - transformers==4.40.1
      - triton==2.3.0
      - truststore==0.8.0
      - types-dataclasses==0.6.6
      - typing_extensions==4.11.0
      - tzdata==2023.3
      - urllib3==1.26.16
      - wandb==0.16.0
      - wcwidth==0.2.13
      - wheel==0.41.2
      - yapf==0.40.2
      - zipp==3.17.0
      - zstandard==0.19.0